v = 1981                  //número
v = 3.14                  // outro número
v = "JavaScript é bacana" //uma string
v = 'JavaScript é legal'  //outra string
v = true                  //boolean true
v = false                 //boolean false
v = /javascript/gi        //expressão regular
v = null                  //null
v = {a: 1, b: 2}          //objeto
v = [1,2,3,4]             //array
